config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    get 'profiles/show'
  end

  get 'profiles/show'

  get 'reviews/new'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'comparisons#compare', as: :authenticated_root
    end

    unauthenticated do
      root :to => 'users/sessions#new', as: :unauthenticated_root
    end
  end
  get 'static_pages/home', to: 'static_pages#home'
  get 'comparisons', to: 'comparisons#compare'
  post 'comparisons', to: 'comparisons#new_review'
  get 'users/profiles/show', to: 'users/profiles#show', as: :user
  get 'users/profiles/show/:response', to: 'users/profiles#show', as: :user_submission
  post '/:integration_name/update-forms', to: 'webhooks#recieve', as: :receive_webhooks
  constraints subdomain: "hooks" do
    post '/:integration_name' => 'webhooks#receive' #as: :receive_webhooks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :forms, dependent: :destroy
  has_many :reviews
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show
    @user = current_user

#    if(!@user || @user.id != params[:id].to_i)
#      redirect_to :unauthenticated_root
#    end
    @forms = @user.forms
    @reviews = Review.where(user_id: @user.id)
    @responses = Form.find(1).responses.order(:rank)

    @display_resp = nil
    #A specific paper has been selected
    if(!params[:response].blank?)
      @display_resp = Form.find(1).responses.find(params[:response].to_i)
      @display_resp_fields = @display_resp.response_properties.reverse #Reverse to display properly in postgres
      @display_resp_name = @display_resp.response_properties.find_by(key_num: "Field2100").response_subproperties

      @response_reviews = Review.where(response1_id: params[:response]).or(Review.where(response2_id: params[:response]))
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/views/users/profiles/show.html.erb
<% provide(:title, "Profile") %>

<% #id_num = @user.id %>

<div class="jumbotron-fluid">
  <div class="container">
    <h1><%= @user.email %></h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3 center">
      <h3> <%= link_to "Overall Ranking", user_path, {style: "color:black"}%> </h3>
    </div>
    <% if @display_resp %>
      <div class="col-md-6 center">
        <h3> <%= "#{@display_resp_name.first.value} #{@display_resp_name.second.value}" %> </h3>
      </div>
      <div class="col-md-3">
        <h3> Reviews </h3>
      </div>
    <% else %>
      <div class="col-md-9 center">
        <h3> Submissions </h3>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3 center">
      <% if @forms.empty? %>
        <p> You don't have any forms associated with your account.</p>
      <% else %>
        <% n = 1 %>
        <% @responses.each do |response| %>
          <% name_array = response.response_properties.find_by(key_num: "Field2100").response_subproperties %>
          <% response_num = response.id %>
          <h4><%= link_to "#{n}: #{name_array.first.value} #{name_array.second.value}", user_submission_path(response_num) %></h4>
          <span>Raw rating: <%= response.rating %></span>
          <% n+=1 %>
          <hr>
        <% end %>
      <% end %>
    </div>
    <% if @display_resp %>
      <div class="col-md-6">
        <% @display_resp_fields.each do |field| %>
          <h4><%= field.key %></h4>
          <% field.response_subproperties.reverse.each do |subfield| %>
            <!-- Excludes labels w/o values  -->
            <% unless subfield.value.blank? %>
              <!-- Print value label, when labels add context -->
              <% unless ((field.response_subproperties.size == 1) ||
                         (subfield.value == subfield.subkey))%>
                <h5 style="display:inline"><%= subfield.subkey + ": " %></h5>
              <% end %>
              <!-- Print value, with added formatting for dates -->
              <% if (field.key.include? "Date") %>
                <span><%= subfield.value[4...6] + "-" + subfield.value[6...8] + "-" + subfield.value[0...4] %></span>
              <% elsif !!subfield.url%>
                <span><%= link_to "#{subfield.value}", subfield.url %></span>
              <% else %>
                <span><%= subfield.value %></span>
              <% end %>
              <p></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% @response_reviews.each do |resp_rev| %>
          <% if (resp_rev.response1_id == @display_resp.id && resp_rev.overall == 1) %>
            <h4 style="display:inline"> Won </h4>
            <% name_array = Response.find(resp_rev.response2_id).response_properties.find_by(key_num: "Field2100").response_subproperties %>
            <% response_num = resp_rev.id %>
            <span>vs. <%= link_to "#{name_array.first.value} #{name_array.second.value}", user_submission_path(response_num) %></span>
            <p>Reviewed by reviewer <%= resp_rev.user_id %></p>
            <hr>
          <% elsif (resp_rev.response2_id == @display_resp.id && resp_rev.overall == 2) %>
            <h4 style="display:inline"> Won </h4>
            <% name_array = Response.find(resp_rev.response1_id).response_properties.find_by(key_num: "Field2100").response_subproperties %>
            <% response_num = resp_rev.id %>
            <span>vs. <%= link_to "#{name_array.first.value} #{name_array.second.value}", user_submission_path(response_num) %></span>
            <p>Reviewed by reviewer <%= resp_rev.user_id %></p>
            <hr>
          <% elsif (resp_rev.response1_id == @display_resp.id && resp_rev.overall == 2)%>
            <h4 style="display:inline"> Lost </h4>
            <% name_array = Response.find(resp_rev.response2_id).response_properties.find_by(key_num: "Field2100").response_subproperties %>
            <% response_num = resp_rev.id %>
            <span>vs. <%= link_to "#{name_array.first.value} #{name_array.second.value}", user_submission_path(response_num) %></span>
            <p>Reviewed by reviewer <%= resp_rev.user_id %></p>
            <hr>
          <% else %>
            <h4 style="display:inline"> Lost </h4>
            <% name_array = Response.find(resp_rev.response1_id).response_properties.find_by(key_num: "Field2100").response_subproperties %>
            <% response_num = resp_rev.id %>
            <span>vs. <%= link_to "#{name_array.first.value} #{name_array.second.value}", user_submission_path(response_num) %></span>
            <p>Reviewed by reviewer <%= resp_rev.user_id %></p>
            <hr>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="col-md-9 center">
        <p> Graphical representation of ratings and error will go here eventually </p>
      </div>
    <% end %>
  </div>
</div>